version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  ui:
    build: ./ui
    image: ${USERNAME}/ui:$(UI_VERSION)
    ports:
      - $(PORT):$(PORT)/tcp
    networks:
      front_net:
        aliases:
          - post_db
          - comment_db
  post:
    build: ./post-py
    image: ${USERNAME}/post:$(POST_VERSION)
    networks:
      - front_net
  comment:
    build: ./comment
    image: ${USERNAME}/comment:$(COMMENT_VERSION)
    networks:
      - front_net

volumes:
  post_db:

networks:
  back_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.2.0/24
  front_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.1.0/24

